### ISSUE TITLE
ArrayIndexOutOfBounds using ServiceLoader with java 9

### ISSUE THREAD

**Issue by brharrington** [FasterXML/jackson-jr#55]
I'm not sure if this is a jackson bug or a java bug, so this might just be an FYI if you haven't encountered it already. So far the jackson-jr-objects jar is the only one that I know causing this problem. Is there anything special about how this jar is created?

Simple test program below, note it doesn't actually use jackson at all but having jackson on the classpath can cause the problem due to the service loader scanning.

```java
import java.util.Iterator;
import java.util.ServiceLoader;

public class Test {
  public static void main(String[] args) throws Exception {
    ServiceLoader<String> loader = ServiceLoader.load(String.class);
    Iterator<String> iter = loader.iterator();
    while (iter.hasNext()) {
      System.out.println(iter.next());
    }
  }
}
```

Results on java 9:

```
$ java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+180)
Java HotSpot(TM) 64-Bit Server VM (build 9+180, mixed mode)
$ java Test
$ java -classpath .:jackson-core-2.9.0.jar Test
$ java -classpath .:jackson-core-2.9.0.jar:jackson-jr-objects-2.9.0.jar Test
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 64
	at java.base/java.util.jar.JarFile.match(JarFile.java:941)
	at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:971)
	at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:366)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:491)
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:447)
	at java.base/jdk.internal.util.jar.JarIndex.getJarIndex(JarIndex.java:115)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:692)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:684)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:683)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:658)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:426)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:409)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:408)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:377)
	at java.base/jdk.internal.loader.URLClassPath.access$000(URLClassPath.java:84)
	at java.base/jdk.internal.loader.URLClassPath$1.next(URLClassPath.java:270)
	at java.base/jdk.internal.loader.URLClassPath$1.hasMoreElements(URLClassPath.java:281)
	at java.base/jdk.internal.loader.BuiltinClassLoader$1.hasNext(BuiltinClassLoader.java:356)
	at java.base/jdk.internal.loader.BuiltinClassLoader$1.hasMoreElements(BuiltinClassLoader.java:364)
	at java.base/java.lang.CompoundEnumeration.next(ClassLoader.java:2921)
	at java.base/java.lang.CompoundEnumeration.hasMoreElements(ClassLoader.java:2930)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1197)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1215)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1259)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1294)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1379)
	at Test.main(Test.java:9)
```

It works fine on java 8:

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ java -classpath .:jackson-core-2.9.0.jar:jackson-jr-objects-2.9.0.jar Test
```

**Comment by cowtowncoder** [comment]
No there is nothing special as far as I know: there isn't even SPI information under `META-INF` directory.
So it would sound like potential Java/JDK 9 bug.

**Comment by brharrington** [comment]
Searching the java bugs I haven't found anything that looks relevant yet. I submitted a java bug report and we'll see how it goes.

**Comment by cowtowncoder** [comment]
Thank you. I hope something turns up; I don't mind making changes if need be.

**Comment by brharrington** [comment]
Looking at it a bit closer it is a bug with JarFile.match for certain characters in the manifest. In this case the problem is the back ticks in the build description. Removing the back ticks is a quick work around. Testing with a jar built locally (see #56 for changes) I no longer see the problem.

**Comment by brharrington** [comment]
FYI: https://bugs.openjdk.java.net/browse/JDK-8186334
