### ISSUE TITLE
strange VerifyError for Emulator.

### ISSUE THREAD

**Issue by Murtowski** [FasterXML/jackson-jr#57]
Hey 
I've tested on emulator api 19 and samsung with api 19
Crash happends on emulator, I'm not quite sure if its fault of jackson or kotlin

```
@Parcelize
@JsonIgnoreProperties(ignoreUnknown = true)
class Damage @JsonCreator constructor(@JsonProperty("eventDate") var date: Date,
             @JsonProperty("eventHour") var time: String, // time may return 15 minuts after XX
             @JsonProperty("eventDescription") var description: String?,
             @Nullable @JsonProperty("status") var status: EnumDamageStatus?,
             @JsonProperty("eventType") var eventType: EnumDamageCircumstances,
             @Nullable @JsonProperty("carRepairShop") var service: CarService?,
             @JsonProperty("processedByCitis") var processedByCitis: Boolean) : Parcelable
```

```
FATAL EXCEPTION: main
                                                                    Process: app.pck.name, PID: 2746
                                                                    java.lang.VerifyError: app.pck.name/model/Damage$Creator
                                                                        at app.pck.name.model.Damage.<clinit>(Damage.kt)
                                                                        at java.lang.Class.getDeclaredConstructors(Native Method)
                                                                        at java.lang.Class.getDeclaredConstructors(Class.java:574)
                                                                        at com.fasterxml.jackson.databind.util.ClassUtil.getConstructors(ClassUtil.java:1114)
                                                                        at com.fasterxml.jackson.databind.introspect.AnnotatedCreatorCollector._findPotentialConstructors(AnnotatedCreatorCollector.java:101)
                                                                        at com.fasterxml.jackson.databind.introspect.AnnotatedCreatorCollector.collect(AnnotatedCreatorCollector.java:56)
                                                                        at com.fasterxml.jackson.databind.introspect.AnnotatedCreatorCollector.collectCreators(AnnotatedCreatorCollector.java:46)
                                                                        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._creators(AnnotatedClass.java:381)
                                                                        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.getConstructors(AnnotatedClass.java:286)
                                                                        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:458)
                                                                        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:313)
                                                                        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
                                                                        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
                                                                        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
                                                                        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
                                                                        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:329)
                                                                        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:313)
                                                                        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:252)
                                                                        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:256)
                                                                        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:179)
                                                                        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
                                                                        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
                                                                        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
                                                                        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
                                                                        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
                                                                        at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:444)
                                                                        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:182)
                                                                        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:27)
                                                                        at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:682)
                                                                        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:482)
                                                                        at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1935)
                                                                        at com.fasterxml.jackson.databind.ObjectReader.<init>(ObjectReader.java:189)
                                                                        at com.fasterxml.jackson.databind.ObjectMapper._newReader(ObjectMapper.java:658)
                                                                        at com.fasterxml.jackson.databind.ObjectMapper.readerFor(ObjectMapper.java:3506)
                                                                        at retrofit2.converter.jackson.JacksonConverterFactory.responseBodyConverter(JacksonConverterFactory.java:60)
                                                                        at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
                                                                        at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
                                                                    	at retrofit2.ServiceMethod$Builder.createR
```

**Comment by cowtowncoder** [comment]
I don't think it is something Jackson controls, since the method is within VM, trying to access bytecode.
So it could be either corrupt byte code or problem in VM. If former, could in theory be something Kotlin compiler had produced I guess.

**Comment by pengrad** [comment]
It's a Kotlin's `@Parcelize`

**Comment by cowtowncoder** [comment]
Not sure what could be done here; closing.
